spring.application.name=BepViet

spring.datasource.url=jdbc:mysql://localhost:3306/BepViet
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.signerKey=BepViet2024SuperSecretKeyForHS512AlgorithmMustBe64CharactersLong!!!
jwt.expiration=3600

spring.output.ansi.enabled=always